/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedVendedorIndexRouteImport } from './routes/_authenticated/vendedor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedVendedorPedidoAssistidoRouteImport } from './routes/_authenticated/vendedor.pedido-assistido'
import { Route as AuthenticatedVendedorMeusPedidosRouteImport } from './routes/_authenticated/vendedor.meus-pedidos'
import { Route as AuthenticatedVendedorClientesRouteImport } from './routes/_authenticated/vendedor.clientes'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin.vendedores'
import { Route as AuthenticatedAdminVendedoresNovoRouteImport } from './routes/_authenticated/admin.vendedores.novo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorIndexRoute =
  AuthenticatedVendedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorPedidoAssistidoRoute =
  AuthenticatedVendedorPedidoAssistidoRouteImport.update({
    id: '/pedido-assistido',
    path: '/pedido-assistido',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorMeusPedidosRoute =
  AuthenticatedVendedorMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorClientesRoute =
  AuthenticatedVendedorClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/admin/vendedores',
    path: '/admin/vendedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVendedoresNovoRoute =
  AuthenticatedAdminVendedoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminVendedoresRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendedor': typeof AuthenticatedVendedorIndexRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/_authenticated/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/_authenticated/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/_authenticated/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/_authenticated/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/sitemap.xml'
    | '/conta'
    | '/pedidos'
    | '/vendedor'
    | '/produto/$slug'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/admin/'
    | '/vendedor/'
    | '/admin/vendedores/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/sitemap.xml'
    | '/conta'
    | '/pedidos'
    | '/produto/$slug'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/admin'
    | '/vendedor'
    | '/admin/vendedores/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/sitemap.xml'
    | '/_authenticated/conta'
    | '/_authenticated/pedidos'
    | '/_authenticated/vendedor'
    | '/produto/$slug'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/vendedor/clientes'
    | '/_authenticated/vendedor/meus-pedidos'
    | '/_authenticated/vendedor/pedido-assistido'
    | '/_authenticated/admin/'
    | '/_authenticated/vendedor/'
    | '/_authenticated/admin/vendedores/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor/': {
      id: '/_authenticated/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof AuthenticatedVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor/pedido-assistido': {
      id: '/_authenticated/vendedor/pedido-assistido'
      path: '/pedido-assistido'
      fullPath: '/vendedor/pedido-assistido'
      preLoaderRoute: typeof AuthenticatedVendedorPedidoAssistidoRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/meus-pedidos': {
      id: '/_authenticated/vendedor/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/vendedor/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedVendedorMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/clientes': {
      id: '/_authenticated/vendedor/clientes'
      path: '/clientes'
      fullPath: '/vendedor/clientes'
      preLoaderRoute: typeof AuthenticatedVendedorClientesRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/admin/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vendedores/novo': {
      id: '/_authenticated/admin/vendedores/novo'
      path: '/novo'
      fullPath: '/admin/vendedores/novo'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminVendedoresRoute
    }
  }
}

interface AuthenticatedVendedorRouteChildren {
  AuthenticatedVendedorClientesRoute: typeof AuthenticatedVendedorClientesRoute
  AuthenticatedVendedorMeusPedidosRoute: typeof AuthenticatedVendedorMeusPedidosRoute
  AuthenticatedVendedorPedidoAssistidoRoute: typeof AuthenticatedVendedorPedidoAssistidoRoute
  AuthenticatedVendedorIndexRoute: typeof AuthenticatedVendedorIndexRoute
}

const AuthenticatedVendedorRouteChildren: AuthenticatedVendedorRouteChildren = {
  AuthenticatedVendedorClientesRoute: AuthenticatedVendedorClientesRoute,
  AuthenticatedVendedorMeusPedidosRoute: AuthenticatedVendedorMeusPedidosRoute,
  AuthenticatedVendedorPedidoAssistidoRoute:
    AuthenticatedVendedorPedidoAssistidoRoute,
  AuthenticatedVendedorIndexRoute: AuthenticatedVendedorIndexRoute,
}

const AuthenticatedVendedorRouteWithChildren =
  AuthenticatedVendedorRoute._addFileChildren(
    AuthenticatedVendedorRouteChildren,
  )

interface AuthenticatedAdminVendedoresRouteChildren {
  AuthenticatedAdminVendedoresNovoRoute: typeof AuthenticatedAdminVendedoresNovoRoute
}

const AuthenticatedAdminVendedoresRouteChildren: AuthenticatedAdminVendedoresRouteChildren =
  {
    AuthenticatedAdminVendedoresNovoRoute:
      AuthenticatedAdminVendedoresNovoRoute,
  }

const AuthenticatedAdminVendedoresRouteWithChildren =
  AuthenticatedAdminVendedoresRoute._addFileChildren(
    AuthenticatedAdminVendedoresRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRouteWithChildren
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRouteWithChildren,
  AuthenticatedAdminVendedoresRoute:
    AuthenticatedAdminVendedoresRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
