/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedVendedorIndexRouteImport } from './routes/_authenticated/vendedor.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedVendedorPedidoAssistidoRouteImport } from './routes/_authenticated/vendedor.pedido-assistido'
import { Route as AuthenticatedVendedorMeusPedidosRouteImport } from './routes/_authenticated/vendedor.meus-pedidos'
import { Route as AuthenticatedVendedorClientesRouteImport } from './routes/_authenticated/vendedor.clientes'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin.vendedores'
import { Route as AuthenticatedAdminPromocoesRouteImport } from './routes/_authenticated/admin.promocoes'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin.produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminMarcasRouteImport } from './routes/_authenticated/admin.marcas'
import { Route as AuthenticatedAdminIaAesBusinessRouteImport } from './routes/_authenticated/admin.ia-aes-business'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin.cupons'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminCadastrosB2bRouteImport } from './routes/_authenticated/admin.cadastros-b2b'
import { Route as AuthenticatedAdminBlingRouteImport } from './routes/_authenticated/admin.bling'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminVendedoresNovoRouteImport } from './routes/_authenticated/admin.vendedores.novo'
import { Route as AuthenticatedAdminProdutosNovoRouteImport } from './routes/_authenticated/admin.produtos.novo'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated/admin.produtos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedVendedorIndexRoute =
  AuthenticatedVendedorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedVendedorPedidoAssistidoRoute =
  AuthenticatedVendedorPedidoAssistidoRouteImport.update({
    id: '/pedido-assistido',
    path: '/pedido-assistido',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorMeusPedidosRoute =
  AuthenticatedVendedorMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedVendedorClientesRoute =
  AuthenticatedVendedorClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedVendedorRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/vendedores',
    path: '/vendedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromocoesRoute =
  AuthenticatedAdminPromocoesRouteImport.update({
    id: '/promocoes',
    path: '/promocoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarcasRoute =
  AuthenticatedAdminMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminIaAesBusinessRoute =
  AuthenticatedAdminIaAesBusinessRouteImport.update({
    id: '/ia-aes-business',
    path: '/ia-aes-business',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCadastrosB2bRoute =
  AuthenticatedAdminCadastrosB2bRouteImport.update({
    id: '/cadastros-b2b',
    path: '/cadastros-b2b',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlingRoute = AuthenticatedAdminBlingRouteImport.update({
  id: '/bling',
  path: '/bling',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminVendedoresNovoRoute =
  AuthenticatedAdminVendedoresNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminVendedoresRoute,
  } as any)
const AuthenticatedAdminProdutosNovoRoute =
  AuthenticatedAdminProdutosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/conta': typeof AuthenticatedContaRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/vendedor': typeof AuthenticatedVendedorIndexRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/bling': typeof AuthenticatedAdminBlingRoute
  '/_authenticated/admin/cadastros-b2b': typeof AuthenticatedAdminCadastrosB2bRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/ia-aes-business': typeof AuthenticatedAdminIaAesBusinessRoute
  '/_authenticated/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/_authenticated/admin/promocoes': typeof AuthenticatedAdminPromocoesRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRouteWithChildren
  '/_authenticated/vendedor/clientes': typeof AuthenticatedVendedorClientesRoute
  '/_authenticated/vendedor/meus-pedidos': typeof AuthenticatedVendedorMeusPedidosRoute
  '/_authenticated/vendedor/pedido-assistido': typeof AuthenticatedVendedorPedidoAssistidoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/vendedor/': typeof AuthenticatedVendedorIndexRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/_authenticated/admin/produtos/novo': typeof AuthenticatedAdminProdutosNovoRoute
  '/_authenticated/admin/vendedores/novo': typeof AuthenticatedAdminVendedoresNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/conta'
    | '/pedidos'
    | '/vendedor'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/banners'
    | '/admin/bling'
    | '/admin/cadastros-b2b'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/ia-aes-business'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/admin/'
    | '/vendedor/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/vendedores/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/conta'
    | '/pedidos'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/banners'
    | '/admin/bling'
    | '/admin/cadastros-b2b'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cupons'
    | '/admin/ia-aes-business'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/promocoes'
    | '/admin/vendedores'
    | '/vendedor/clientes'
    | '/vendedor/meus-pedidos'
    | '/vendedor/pedido-assistido'
    | '/admin'
    | '/vendedor'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/vendedores/novo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/b2b'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/conta'
    | '/_authenticated/pedidos'
    | '/_authenticated/vendedor'
    | '/produto/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/bling'
    | '/_authenticated/admin/cadastros-b2b'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/ia-aes-business'
    | '/_authenticated/admin/marcas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/promocoes'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/vendedor/clientes'
    | '/_authenticated/vendedor/meus-pedidos'
    | '/_authenticated/vendedor/pedido-assistido'
    | '/_authenticated/admin/'
    | '/_authenticated/vendedor/'
    | '/_authenticated/admin/produtos/$id'
    | '/_authenticated/admin/produtos/novo'
    | '/_authenticated/admin/vendedores/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendedor/': {
      id: '/_authenticated/vendedor/'
      path: '/'
      fullPath: '/vendedor/'
      preLoaderRoute: typeof AuthenticatedVendedorIndexRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/vendedor/pedido-assistido': {
      id: '/_authenticated/vendedor/pedido-assistido'
      path: '/pedido-assistido'
      fullPath: '/vendedor/pedido-assistido'
      preLoaderRoute: typeof AuthenticatedVendedorPedidoAssistidoRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/meus-pedidos': {
      id: '/_authenticated/vendedor/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/vendedor/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedVendedorMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/vendedor/clientes': {
      id: '/_authenticated/vendedor/clientes'
      path: '/clientes'
      fullPath: '/vendedor/clientes'
      preLoaderRoute: typeof AuthenticatedVendedorClientesRouteImport
      parentRoute: typeof AuthenticatedVendedorRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promocoes': {
      id: '/_authenticated/admin/promocoes'
      path: '/promocoes'
      fullPath: '/admin/promocoes'
      preLoaderRoute: typeof AuthenticatedAdminPromocoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marcas': {
      id: '/_authenticated/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AuthenticatedAdminMarcasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ia-aes-business': {
      id: '/_authenticated/admin/ia-aes-business'
      path: '/ia-aes-business'
      fullPath: '/admin/ia-aes-business'
      preLoaderRoute: typeof AuthenticatedAdminIaAesBusinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cadastros-b2b': {
      id: '/_authenticated/admin/cadastros-b2b'
      path: '/cadastros-b2b'
      fullPath: '/admin/cadastros-b2b'
      preLoaderRoute: typeof AuthenticatedAdminCadastrosB2bRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bling': {
      id: '/_authenticated/admin/bling'
      path: '/bling'
      fullPath: '/admin/bling'
      preLoaderRoute: typeof AuthenticatedAdminBlingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/vendedores/novo': {
      id: '/_authenticated/admin/vendedores/novo'
      path: '/novo'
      fullPath: '/admin/vendedores/novo'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresNovoRouteImport
      parentRoute: typeof AuthenticatedAdminVendedoresRoute
    }
    '/_authenticated/admin/produtos/novo': {
      id: '/_authenticated/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AuthenticatedAdminProdutosNovoRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
  }
}

interface AuthenticatedAdminProdutosRouteChildren {
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
  AuthenticatedAdminProdutosNovoRoute: typeof AuthenticatedAdminProdutosNovoRoute
}

const AuthenticatedAdminProdutosRouteChildren: AuthenticatedAdminProdutosRouteChildren =
  {
    AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
    AuthenticatedAdminProdutosNovoRoute: AuthenticatedAdminProdutosNovoRoute,
  }

const AuthenticatedAdminProdutosRouteWithChildren =
  AuthenticatedAdminProdutosRoute._addFileChildren(
    AuthenticatedAdminProdutosRouteChildren,
  )

interface AuthenticatedAdminVendedoresRouteChildren {
  AuthenticatedAdminVendedoresNovoRoute: typeof AuthenticatedAdminVendedoresNovoRoute
}

const AuthenticatedAdminVendedoresRouteChildren: AuthenticatedAdminVendedoresRouteChildren =
  {
    AuthenticatedAdminVendedoresNovoRoute:
      AuthenticatedAdminVendedoresNovoRoute,
  }

const AuthenticatedAdminVendedoresRouteWithChildren =
  AuthenticatedAdminVendedoresRoute._addFileChildren(
    AuthenticatedAdminVendedoresRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBlingRoute: typeof AuthenticatedAdminBlingRoute
  AuthenticatedAdminCadastrosB2bRoute: typeof AuthenticatedAdminCadastrosB2bRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminIaAesBusinessRoute: typeof AuthenticatedAdminIaAesBusinessRoute
  AuthenticatedAdminMarcasRoute: typeof AuthenticatedAdminMarcasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRouteWithChildren
  AuthenticatedAdminPromocoesRoute: typeof AuthenticatedAdminPromocoesRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminBlingRoute: AuthenticatedAdminBlingRoute,
  AuthenticatedAdminCadastrosB2bRoute: AuthenticatedAdminCadastrosB2bRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
  AuthenticatedAdminIaAesBusinessRoute: AuthenticatedAdminIaAesBusinessRoute,
  AuthenticatedAdminMarcasRoute: AuthenticatedAdminMarcasRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRouteWithChildren,
  AuthenticatedAdminPromocoesRoute: AuthenticatedAdminPromocoesRoute,
  AuthenticatedAdminVendedoresRoute:
    AuthenticatedAdminVendedoresRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendedorRouteChildren {
  AuthenticatedVendedorClientesRoute: typeof AuthenticatedVendedorClientesRoute
  AuthenticatedVendedorMeusPedidosRoute: typeof AuthenticatedVendedorMeusPedidosRoute
  AuthenticatedVendedorPedidoAssistidoRoute: typeof AuthenticatedVendedorPedidoAssistidoRoute
  AuthenticatedVendedorIndexRoute: typeof AuthenticatedVendedorIndexRoute
}

const AuthenticatedVendedorRouteChildren: AuthenticatedVendedorRouteChildren = {
  AuthenticatedVendedorClientesRoute: AuthenticatedVendedorClientesRoute,
  AuthenticatedVendedorMeusPedidosRoute: AuthenticatedVendedorMeusPedidosRoute,
  AuthenticatedVendedorPedidoAssistidoRoute:
    AuthenticatedVendedorPedidoAssistidoRoute,
  AuthenticatedVendedorIndexRoute: AuthenticatedVendedorIndexRoute,
}

const AuthenticatedVendedorRouteWithChildren =
  AuthenticatedVendedorRoute._addFileChildren(
    AuthenticatedVendedorRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
